### ISSUE TITLE
Add-on submissions maybe merged in the next transformation

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/addon-datastore#1138]
@seanbudd : for an example, see this [workflow run](https://github.com/nvaccess/addon-datastore/actions/runs/5603883578/job/15181567726). In this case, Windows App Essentials 23.07.40 (beta was merged in the next commit.

I think that concurrency with cancel-in-progress: true would avoid these situations..

[sample workflow using concurrency](https://raw.githubusercontent.com/ankush56/helloWorld/c10e984c94bcb628069961088c6132a2381077a2/.github/workflows/concurrency.yml).

**Comment by seanbudd** [comment]
Could you please explain the issue more thoroughly?
Is data not being transformed accurately?

**Comment by nvdaes** [comment]
as shown in tfc mentioned run, Windows App Essential was merged in the views branch in the next commit, along with the dictionaries add-ons. The workflow could not push changes since another workflow was pushing at the same time and changes weren"t not pulled. So, if concurrency is used, two workflows won"t try to push at the same time. @josephsl sent two add-ons consecutively, so two workflows try to push without pulling changes and so the second was rejected.Enviado desde mi iPhoneEl 21 jul 2023, a las 2:00, Sean Budd ***@***.***> escribió:﻿
Could you please explain the issue more thoroughly?
Is data not being transformed accurately?

**Comment by seanbudd** [comment]
I don't see how this is an issue - as long as the latest data is successfully transformed

**Comment by nvdaes** [comment]
Íf the dictionaries add-on was sent a week afther Windows App >essential dev and beta, the beta version wouldn"t be presented in the store until a week later, since Github Actions failed for beta, due to a fast consecutive submission by Joseph. I read that the github workflow failed since another workflow was pushing probably at the same time, and the seccond one didn"t make a pull before pushing. Concurrency may fix this since the first github workflow would be cancelled and just the latest would try to push to the views branch.Enviado desde mi iPhoneEl 21 jul 2023, a las 2:17, Sean Budd ***@***.***> escribió:﻿
I don't see how this is an issue - as long as the latest data is successfully transformed in the end

**Comment by XLTechie** [comment]
I agree with @nvdaes. The delay could potentially be extensive, and the solution 
at least appears simple.

If it is less straight forward, perhaps an alternative would be an once-per hour 
cronjob workflow trigger, to clean up anything unmerged?

**Comment by seanbudd** [comment]
Thanks for explaining - it wasn't immediately clear from the description that this could cause data to not reach the views indefinitely

**Comment by nvdaes** [comment]
Hello: Here¡sanother example of failure related to this issue:

https://github.com/nvaccess/addon-datastore/actions/runs/5699213975/job/15447900996

**Comment by nvdaes** [comment]
@seanbudd , this problem has been observed at least two more times. If I can help with a PR using concurrency let me know. I don't know if you prefer to test this in the add-ondatastore stage repo, and if we should use cancel in progress or not, since both options will fix this, I think.

**Comment by seanbudd** [comment]
If you'd like to contribute this fix, you are very welcome to. I think cancelling the transformation step is fine, though I haven't had a chance to explore the options and their effects.

Any changes to the submission process should be tested it in your own fork(s), like `addon-datastore-staging`, with successful test submissions linked for the review process.

**Comment by nvdaes** [comment]
I'll test this on my fork with and without cancel in progress, and I may create a PR here.

**Comment by XLTechie** [comment]
@nvdaes, keep in mind that if you don't use cancel-in-progress, it will queue, 
at most, one job. So the case of jobs being cancelled still needs to be 
accounted for, because if three jobs are called, the middle job(s) will never 
run.

Which is probably fine, as long as the last one is guaranteed to pick up changes 
that would have been in the middle one.

Personally I think not cancelling is better, if it will work for our situation, 
but just pointing out the oddity of what it does.

  From the docs:

When a concurrent job or workflow is queued, if another job or workflow using 
the same concurrency group in the repository is in progress, the queued job or workflow will be pending. Any previously pending job or workflow in 
the concurrency group will be canceled. To also cancel any currently running job or workflow in the same concurrency group, specify cancel-in-progress: 
true.

**Comment by nvdaes** [comment]
Thanks Luke. I think it's better to use cancel-in-progress, so that if 
the transformDataToViews workflow is triggered manually and it's another 
workflow in progress, it can be cancelled as well and just the last 
workflow is run. Though I think that the result will be the same, so 
it's not important.
