### ISSUE TITLE
[Submit add-on]: whiteNoise

### ISSUE THREAD

**Issue by albzan** [nvaccess/addon-datastore#1188]
### Download URL

https://github.com/albzan/whiteNoise/releases/download/0.2/whiteNoise-0.2.nvda-addon

### Source URL

https://github.com/albzan/whiteNoise

### Publisher

Alberto Zanella

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by seanbudd** [comment]
Please note the following error and resubmit a valid add-on version

https://github.com/nvaccess/addon-datastore/pull/1189#issuecomment-1653331502
