### ISSUE TITLE
[Submit add-on]: SpeaKey

### ISSUE THREAD

**Issue by albzan** [nvaccess/addon-datastore#1190]
### Download URL

https://github.com/albzan/SpeaKey/releases/download/1.1/SpeaKey-1.1.nvda-addon

### Source URL

https://github.com/albzan/SpeaKey

### Publisher

Alberto Zanella

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by seanbudd** [comment]
Please note the following error and resubmit a valid add-on version

https://github.com/nvaccess/addon-datastore/pull/1191#issuecomment-1653333601
