### ISSUE TITLE
[Submit add-on]: lambda

### ISSUE THREAD

**Issue by albzan** [nvaccess/addon-datastore#1192]
### Download URL

https://github.com/lambda-nvda/lambdaNvda/releases/download/1.4.2/lambda-1.4.2.nvda-addon

### Source URL

https://github.com/lambda-nvda/lambdaNvda

### Publisher

lambda-nvda

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by seanbudd** [comment]
This failed due to a legacy add-on being registered. Attempting to re-submit on your behalf.

**Comment by albzan** [comment]
Thank you!
