### ISSUE TITLE
[Submit add-on]: eclipseEnhance

### ISSUE THREAD

**Issue by albzan** [nvaccess/addon-datastore#1196]
### Download URL

https://github.com/albzan/eclipse-nvda/releases/download/0.8/eclipseEnhance-0.8.nvda-addon

### Source URL

https://github.com/albzan/eclipse-nvda

### Publisher

Alberto Zanella

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by seanbudd** [comment]
Please note the following error and resubmit a valid add-on version

https://github.com/nvaccess/addon-datastore/pull/1197#issuecomment-1653359428
