### ISSUE TITLE
[Submit add-on]: edico

### ISSUE THREAD

**Issue by albzan** [nvaccess/addon-datastore#1247]
### Download URL

https://github.com/edicoitalia/edico-nvda/releases/download/1.2/edico-1.2.nvda-addon

### Source URL

https://github.com/edicoitalia/edico-nvda

### Publisher

edicoitalia.it

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by nvdaes** [comment]
Thanks a lot for this add-on! I installed Edico but I was not able to read and so I didn't request for a license to ONCE.
😄

**Comment by albzan** [comment]
Hi Noelia,

You're welcome, and I'm open to contributions for this!
Feel free to try it and let me know if you find something to be improved.
Feel free also to submit via PR.
Thank you!
Bye,
Alberto

Il giorno dom 30 lug 2023 alle ore 11:59 Noelia Ruiz Martínez <
***@***.***> ha scritto:

**Comment by nvdaes** [comment]
Sure, I'll try it the next week and also other add-ons sent by you like 
White noise!

Bye.
