### ISSUE TITLE
NVDA 2024.1 alpha: available and updatable add-ons lists are empty despite enabling looking for incompatible add-ons

### ISSUE THREAD

**Issue by josephsl** [nvaccess/addon-datastore#1528]
Hi,

This may not be relevant until API incompatibility flag is included in NVDA alpha:

### Description
In add-on store, availble and updatable add-ons are not showing if running 2024.1 alpha an with include incompatible add-ons checked.

### Steps to reproduce;
1. Install alpha builds such as alpha.29111.
2. Open NV Access add-on store 9NVDA menu/tools/add-on store).
3. Go to available add-ons tab.
4. Check "include incompatible add-ons" checkbox.
5. Press Alt+A to move to available add-ons list.

Expected: add-ons list is populated with available add-ons despite most of them being incompatible with 2024.1 API.

Actual: add-ons list is empty.

Impact: people using alphas and relying on add-on store will not see updatable add-ons. As a workaround, people must install add-ons from outside the store e.g. visiting release pages.

### Possible solution:
We can refine incompatible add-ons check, and if that checkbox is checked, use "latest" endpoint instead of version (e.g. 2024.1.0) endpoint. Or, we can add 2024.1 API to the API json file when NVDA alpha updates backwards compatible flag to 2024.1 in the future.

Thanks.

**Comment by seanbudd** [comment]
This should be fixed now that https://github.com/nvaccess/nvda/pull/15367 has been merged.

I've updated our internal release process so that we update the API backwards compatibility as part of bumping the build version so this shouldn't happen again
