### ISSUE TITLE
[Submit add-on]: crash hero

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/addon-datastore#1927]
### Download URL

https://github.com/derekriemer/nvda-crashHero/releases/download/release-2.0.3-retry2/crashHero-2.0.3.nvda-addon

### Source URL

acks.mozilla.org/

### Publisher

Derek Riemer

### Channel

beta

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by nvdaes** [comment]
Hi @derekriemer , can you please remove this version or replace it? The source code webpage is wrong. Cheers

**Comment by derekriemer** [comment]
wow, I suppose the copy paste I envoked simply didn't work. Why does the template generate a json? Can I not just upload that file somewhere?
