### ISSUE TITLE
Nao

### ISSUE THREAD

**Issue by dreinn** [nvaccess/addon-datastore#1943]
### Download URL

https://github.com/sharkboyto/nao/releases/download/v_2023.1.1/nao-2023.1.1.nvda-addon

### Source URL

https://github.com/sharkboyto/nao

### Publisher

Alessandro Albano<ale.albano1980@gmail.com>, Davide De Carne<davide.dec@gmail.com> and Simone Dal Maso<simone.dalmaso@gmail.com>

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by seanbudd** [comment]
@nvdaes - there is another regression introduced, this workflow failed to run https://github.com/nvaccess/addon-datastore/actions/runs/6739552435

**Comment by nvdaes** [comment]
@seanbudd and @dreinn , I'm trying to fix this making tests, unquoting the add-on id. @seanbudd , if you consider appropriate to fix it yourself to be faster than me,please feel free to do it, to avoid delays in the add-on submission process.
