### ISSUE TITLE
[Submit add-on]: newfon 2.0

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/addon-datastore#200]
### Download URL

https://github.com/DraganRatkovich/newfon/releases/download/2023.2.0/Newfon-2023.2.0.nvda-addon

### Source URL

https://github.com/DraganRatkovich/newfon/

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by nvdaes** [comment]
cc: @DraganRatkovich Let's see what happens, hope this works.

**Comment by DraganRatkovich** [comment]
@nvdaes I think at this point you should already be receiving some kind of notification of a successful PR merge, as well as any failure.

**Comment by nvdaes** [comment]
Hello, I think that the problem is that your addon name is capitalized, but a newfon folder in lowercase still exist, so Windows cannot create the folder with capitalized name. You may create an add-on named newfon in lowercase and try again.
