### ISSUE TITLE
[Submit add-on]: newfon 23.2.0

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/addon-datastore#207]
### Download URL

https://github.com/DraganRatkovich/newfon/releases/download/2023.2.0/newfon-2023.2.0.nvda-addon

### Source URL

https://github.com/DraganRatkovich/newfon/

### Channel

stable

### License Name

MIT

### License URL

https://mit-license.org

**Comment by nvdaes** [comment]
@DraganRatkovich This is merged. Sometimes the views branch copies a submission when the next add-on is submitted, and this has been the case here. I've put MIT license with its URL. I think that the problem maybe that, if license URL is not specified, the issue form field is set to No response. But I'm not sure. I'll investigate this.

**Comment by DraganRatkovich** [comment]
@nvdaes First of all, thanks for helping me merge. Please let me know if you can find more information on this issue as I changed the license and its url several times today and still got the same error.

**Comment by DraganRatkovich** [comment]
Hello,

@nvdaes Just to clarify a few things, did you open an issue and generate the json file from an automatic process, or did you open a PR in a new branch and AutoMerge merged the PR into master? So, in the future, if I want to change something but don't want to change the version number, should I only change the existing json file and push it through a new branch, or is there some other step that I should take into account? Also, what should the branch name be if I want to push it through a new branch? As before, we did it through the old process, should it be called addon_name-addon_version, or is the add-on store using some other format?

**Comment by XLTechie** [comment]
On Mar 11, DraganRatkovich wrote:

> So, in the future, if I want to change something but don't want to change the version number, should I only change the

What is the scenario for changing "something" without changing the version 
number?

Version numbers are cheap, especially now that the updates are immediate and we 
don't have to wait weeks for the old PR review and approval process.

**Comment by DraganRatkovich** [comment]
@XLTechie So yesterday there were several attempts to submit the addon both from the issue form and via the open PR from the new branch, both failed. Not entirely sure what the problem was. Also, if I change the version number, which I will definitely do now since the license has changed a bit, should I delete the old json files or just add a new json file with the version number changed.

**Comment by XLTechie** [comment]
I can't answer that--I have not explored the PR based submission process under 
the latest workflows. But you can probably look at what has been done for other 
add-ons that have recently updated versions, and do whatever that is. Or wait 
for @nvdaes to answer.

I also had trouble with a couple submission attempts. Since they failed, I kept 
the same version number in the new attempts. I think that may be okay. But once 
a version is merged, you have to do a new version number, even for really tiny 
changes. That is as it should be, since to do otherwise can really confuse users 
and automated systems alike.

We had that happen many times under the old system, where someone would make a 
little bugfix on a newly released version, without changing the version number 
or the URL, and which version you got depended on which minute you downloaded. 
That is no good.

**Comment by nvdaes** [comment]
Hello: If something is changed in the add-on, you have to release a new version even if the change is very small like a line in the documentation included in the add-on. I just fill in the form issue and the branch and pull request is automatically created and merged. See the guide for submitters for more info. Note that this thread has various messages and I"ve been replying to the direct question to me. I"m not reading all due to time management. I"m happy to help with direct questions and provide assistance if you need that I send more add-ons on your behalf. Hope this helps.Enviado desde mi iPhoneEl 12 mar 2023, a las 5:58, DraganRatkovich ***@***.***> escribió:﻿
Hello,
@nvdaes Just to clarify a few things, did you open an issue and generate the json file from an automatic process, or did you open a PR in a new branch and AutoMerge merged the PR into master? So, in the future, if I want to change something but don't want to change the version number, should I only change the existing json file and push it through a new branch, or is there some other step that I should take into account? Also, what should the branch name be if I want to push it through a new branch? As before, we did it through the old process, should it be called addon_name-addon_version, or is the add-on store using some other format?

**Comment by DraganRatkovich** [comment]
Hi,

Luckily, the release I submitted was successful and it was merged🙂 @nvdaes @XLTechie Thanks again for your valuable help and information.

**Comment by nvdaes** [comment]
Great! Thank you.Enviado desde mi iPhoneEl 12 mar 2023, a las 15:50, DraganRatkovich ***@***.***> escribió:﻿
Hi,
Luckily, the release I submitted was successful and it was merged🙂 @nvdaes @XLTechie Thanks again for your valuable help and information.

**Comment by DraganRatkovich** [comment]
@nvdaes I didn't see anything in the submission guide about this, so I figured I'd ask here. How should add-ons be submitted via the add-on store repository that has never been submitted to the community website? Will opening a issue automatically do the rest of the work on the get.php file, or is it a big page of the past?

**Comment by nvdaes** [comment]
Hello: New add-ons can be sent to the store in the same way, and a link to the website will be generated. However, if you want to add a webpage for your add-on on the website,you have to add it in the Translations repo. Please see info on the add-ons website. I've updated the documentation, though I have to fix some links.
You can see the design overview page linked in the addondatastore readme to see the form of the URL that you can use for links of your add-ons.
Hope this helps.

**Comment by DraganRatkovich** [comment]
@nvdaes Everything is clear, thank you very much.

**Comment by DraganRatkovich** [comment]
@nvdaes Could you please link to the exact repo where I can read how to add a website to the translations repository. I can't find it on the NVDA wiki or maybe I missed something.

**Comment by nvdaes** [comment]
https://addons.nvda-project.org/requirements.en.html

çThere isa link to the repo.

2023-03-12 19:35 GMT+01:00, DraganRatkovich ***@***.***>:
