### ISSUE TITLE
[Submit add-on]: Submitting Search With version 2.4

### ISSUE THREAD

**Issue by ibrahim-s** [nvaccess/addon-datastore#216]
### Download URL

https://github.com/ibrahim-s/searchWith/releases/download/2.4/searchWith-2.4.nvda-addon

### Source URL

https://github.com/ibrahim-s/searchWith/

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by ibrahim-s** [comment]
Submition failed

**Comment by seanbudd** [comment]
Closing as an alternative submission had passed
