### ISSUE TITLE
Discussion: removing legacy add-on ID's

### ISSUE THREAD

**Issue by josephsl** [nvaccess/addon-datastore#218]
Hi,

The following is considered a near-term goal:

Currently the add-on datastore contains multiple entries for the same add-on due to the migration from old add-on files repository to the datastore. For example, Add-on Updater is listed under both "nvda3208" (old add-on ID) and "addonUpdater" (new and official add-on ID). While we can use download links (repo addresses) to figure out how many add-ons are actually registered, presence of legacy and actual datastore entries can cause miscalculation of actual add-on count for various purposes such as statistics. Therefore, it is proposed to remove legacy add-on ID's from the datastore, subject to notes from authors/publishers to make the add-on count more realistic and to standardize on using add-on name field found in the actual add-on manifest as actual add-on ID.

Specifically:

1. Survey add-ons community and authors about which add-on ID's should be used as official ID's.
2. For ID's coming from legacy add-on files repository, ask authors and/or publishers about keeping or removing them.
3. If authors request removing legacy add-on ID's, the author and/or someone should create a pull request to remove legacy ad-on ID's. The pull request comment must specify the legacy add-on ID being removed and the new (official) add-on ID to be used from then on.
4. If the author chooses to use a different ID (say, the official add-on ID registered more recently), documentation such as community add-ons website must direct users to the new add-on download links via the official add-on ID.

Requirements:

* Multiple entries for the same add-on must be present in the add-on datastore.
* At least one duplicate entry must be a legacy add-on ID from now archived add-on files repository.
* Add-on author/publisher specifies which add-on ID to be used as official and whether to keep the legacy ID's or not, along with actions to be taken such as updating documentation.
* One pull request per add-on, including unifying multiple add-on ID's for the same add-on into one.

Ideal timeline and process:

* Now: add-on author/publisher identifies add-ons with multiple datastore entries, including entries coming from add-on files repository and marked as legacy. Data should be added as a comment on this issue.
* At least a week after NVDA 2023.1 stable version is released: start working on pull requests to remove legacy add-on ID's if authors/publishers specify it.
* Very close to publication of release candidate for NVDA release with add-on store included: complete legacy add-on ID removal process.

Thanks.

**Comment by XLTechie** [comment]
@josephsl

I have no objection to your proposed process, but one question:

>  2. For ID's coming from legacy add-on files repository, ask authors and/or publishers about keeping or removing them.

My understanding was that the only reason anyone had to use the shortform IDs to 
begin with, was because Ikiwiki couldn't handle longer IDs in translated URIs.

If that's the case, and we don't care about that any more, why shouldn't NV 
Access just mandate what kind of IDs they want, and the community adapt the data 
accordingly?

Put another way: why is this a choice that developers should make, over just 
choosing what would be the best practice going forward and requiring it?

**Comment by josephsl** [comment]
Hi,

Ikiwiki: I did test Enhanced Touch Gestures download link with various languages and found no issues downloading the add-on using the now official add-on ID link. Internally, what Ikiwiki will do is convert po files into Markdown before publishing docs on community add-ons website, and for add-on authors, translated readme.md files will be included when pulling in translations data.

I understand that some shorthands are used to house older add-ons for folks needing it, or tools may rely on them for various reasons - it is up to authors to let us know if this is no longer needed. This is the reason for letting authors/publishers tell us about legacy ID's and what to do with them.

As far as my add-ons (active and end of life) are concerned, legacy add-on ID's except Windows App Essentials (w10) can be removed. Specifically, this will involve:

* Add-on Updater: nvda3208 -> addonUpdater
* Enhanced Touch Gestures: ets -> enhancedTouchGestures
* GoldWave: gwv -> goldwave
* Object Location Tones: objLoc -> objLocTones
* Resource Monitor: rm -> resourceMonitor
* StationPlaylist: spl -> stationPlaylist
* Windows App Essentials: w10 -> wintenApps

Regarding Windows App Essentials legacy ID (w10), I'm waiting for a mechanism to let the legacy addonslist endpoint inform tools such as Add-on Updater that development releases are available via wintenApps-dev key or something similar. This won't matter much though once add-on store becomes part of a future NVDA release, and I imagine add-on update check mechanism in NVDA (core, that is) can use add-on name as defined in the manifest, compare that with add-on ID's, then inform users about updates - after all, this is add-on update check protocol 4 as defined in Add-on Updater (the add-on datastore protocol will check add-on names/ID's).

Thanks.

**Comment by josephsl** [comment]
Access8Math: legacy endpoint is "access8math" whereas add-on name/ID from the manifest says "Access8Math". Although this one is not really related to this discussion, but it would be helpful to document cases like this so people can resolve upper versus lower case first before doing anything else with affected add-ons. Thanks.

**Comment by seanbudd** [comment]
I am going to close this:
- we have a [migration guide](https://github.com/nvaccess/addon-datastore/pull/299) for moving away from legacy add-ons,
- We have made legacy a field in the JSON: https://github.com/nvaccess/addon-datastore-validation/pull/28
- we have marked add-ons as legacy using the field: https://github.com/nvaccess/addon-datastore/pull/571
- legacy add-ons are not shown in the NVDA add-on store, only via the community add-ons website and other external sources: https://github.com/nvaccess/nvda/pull/14882

**Comment by josephsl** [comment]
Hi, thanks for taking care of documentation work. I’m sure folks would submit pull requests to remove legacy add-on ID’s in the future. Thanks again for your hard work.
