### ISSUE TITLE
Some add-ons are added to views branch in the next submission

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/addon-datastore#219]
### Problem

Finally, add-ons are  copied to the views branch as required, but sometimes this is done when another add-on is sent

### Posible suggestion

transformDataToViews.yml workflow maybe run on schedule for example every hour instead of running it when PRs are marged?
Cheers.

**Comment by josephsl** [comment]
Hi,

Specifically, when the second to last add-on submission is merged. I have verified this through:

1. Submit Windows App Essentials 23.03.1.
2. Wait for TeleNVDA to be merged.
3. Views branch merges data from Windows App Essentials add-on submission.
4. Submit Add-on Updater 23.03.4 to the store.
5. TeleNVDA data gets merged into views branch.

An hourly merge seems fine unless an urgent update must be released. Thanks.

**Comment by seanbudd** [comment]
Is batch updating a problem?

When we designed this, it was expected that the transformation to views may get batched when there are many PRs merged at the same time.

**Comment by josephsl** [comment]
For me, batching won't be a problem as I may need to release my add-ons onto all three release channels (dev, beta, stable). There could be some technical issues people might bring up.

Thanks.

**Comment by seanbudd** [comment]
Closing this as not an issue then, I don't see a reason to implement changes here.

**Comment by nvdaes** [comment]
Hi Sean, can you explain why this is completed? If someone sends an add-on, it won"t be merged until another add-on is sent, and the last add-on is never been included in the store. You may schedule this to be run every day or every hour; sorry if I"m missing something.

**Comment by josephsl** [comment]
Do keep in mind that the original issue at hand was no appearance of the just submitted add-on that has passed e.g. latest version of the add-on ont appearing in views branch riht after validation passes but rather it appears after another add-on is submitted and is validated. Thanks.

**Comment by seanbudd** [comment]
>Hi Sean, can you explain why this is completed? If someone sends an add-on, it won"t be merged until another add-on is sent, and the last add-on is never been included in the store. You may schedule this to be run every day or every hour; sorry if I"m missing something.

My mistake, I thought an issue was occurring where if multiple submissions occurred simultaneously, only the last one would would transform the data. I was unaware that each transformation was a commit behind on master.
This should be fixed via #289 by adding `fetch-depth: 0` to clear the cache.

**Comment by nvdaes** [comment]
Great, thanks.
