### ISSUE TITLE
[Submit add-on]: noBeepsSpeechMode 5.5

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/addon-datastore#2448]
### Download URL

https://github.com/ABuffEr/noBeepsSpeechMode/releases/download/v5.5/noBeepsSpeechMode-5.5.nvda-addon

### Source URL

https://github.com/ABuffEr/noBeepsSpeechMode

### Publisher

Alberto Buffolino

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by nvdaes** [comment]
@ABuffEr , I'm testing on my fork now. Seems that now this will require fromJSON function in GitHub Actions, I don't know why. Maybe the transition of GitHub to Node20 for GitHub Actions. No idea

**Comment by seanbudd** [comment]
this issue should be fixed now. Please resubmit. Thanks
