### ISSUE TITLE
[Submit add-on]: wintenapps dev

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/addon-datastore#2454]
### Download URL

https://github.com/josephsl/wintenApps/releases/download/24.02/wintenApps-20240202.0.0.nvda-addon

### Source URL

https://github.com/josephsl/wintenapps

### Publisher

josephsl

### Channel

dev

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by seanbudd** [comment]
this issue should be fixed now. Please resubmit. Thanks
