### ISSUE TITLE
[Submit add-on]: Review Cursor Copier 1.6

### ISSUE THREAD

**Issue by tuukkao** [nvaccess/addon-datastore#2539]
### Download URL

https://github.com/tuukkao/nvda-reviewCursorCopier/releases/download/1.6/reviewCursorCopier-1.6.nvda-addon

### Source URL

https://github.com/tuukkao/nvda-reviewCursorCopier/

### Publisher

Tuukka Ojala

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by tuukkao** [comment]
Closed because of incorrect release title.

**Comment by jmdaweb** [comment]
For the next time, you should use the beta or dev channels. Otherwise, if the add-on is compatible with 2024.1, it will be automatically rejected. The store will start accepting stable add-ons once NVDA 2024.1 rc1 is released.
