### ISSUE TITLE
Please delete old version announcements in existing add-on reviews

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/addon-datastore#2578]
The scripts no longer post a new version announcement for each uploaded version of an add-on, to the reviews discussion for that add-on.

However, the old announcements for these are still cluttering up the old forms.

I request that NV Access go through and delete all of these, or do so programmatically if that is possible. (Or, give me permissions and I will happily go through and do it, as these make the reviews pages quite unpleasant!)

As an example, I just left a review for Windows App Essentials. There were something like 14 comments on that review before mine, and every single one of them is a new version announcement!

**Comment by seanbudd** [comment]
@XLTechie - if you are happy to address this and https://github.com/nvaccess/addon-datastore/issues/2579, we can temporarily grant you write permissions to this repository. Can you please outline a window when you intend to do this so that we can limit the elevated permission period.

**Comment by XLTechie** [comment]
@seanbudd, I'll make a list of all effected discussions, and get back to you 
with a time estimate.

**Comment by XLTechie** [comment]
@seanbudd I can work on this tonight and Saturday night, or Saturday night and Sunday night, depending on when you enable the access.

**Comment by seanbudd** [comment]
Hi @XLTechie - I've granted you permissions now, happy to leave them on for the next week or so

**Comment by seanbudd** [comment]
Please let me know when you're done

**Comment by XLTechie** [comment]
> Please let me know when you're done

Will do. Thanks.

**Comment by XLTechie** [comment]
@seanbudd Some notes:

1. I am finished resolving these, feel free to revoke access.
2. While at it, I noticed that #2031  was the same as 2030 (both for Resource Monitor). I checked the store, and 2031 is what is referenced in the JSON. I closed 2030 as duplicate, but then noticed how to delete it, so did that.
3. I didn't want to unilaterally do anything about it, but you may want to hide or delete the off topic comment(s) in #2023.

**Comment by XLTechie** [comment]
The discussions have been cleaned of undesirable version announcements as of March 8th 2024 at 23:30 EDT.

#### Effected review discussions:

#1942
#1947
#1950
#1954
#1962
#1963
#1965
#1976
#1981
#1989
#1992
#1995
#1998
#2001
#2016
#2020
#2023
#2025
2030
#2031
#2034
#2039
#2043
#2048
#2052
#2056
#2065
#2072
#2075
#2078
#2090

**Comment by seanbudd** [comment]
Thanks - I think we can leave those comments as is
