### ISSUE TITLE
[Submit add-on]: 

### ISSUE THREAD

**Issue by NSoiffer** [nvaccess/addon-datastore#277]
### Download URL

https://github.com/NSoiffer/MathCATForPython/releases/download/0.2.1/MathCAT-0.2.0.1.nvda-addon

### Source URL

https://github.com/NSoiffer/MathCATForPython

### Channel

stable

### License Name

GPL v2 + MIT

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by josephsl** [comment]
If this is being submitted via old lowercase ad-don ID, PLEASE HOLD OFF UNTIL LOWERCASE To UPPERCASE/CAMEL CASE CONVERSION IS COMPLETE!

**Comment by NSoiffer** [comment]
To be honest, I built it a few weeks ago and forgot to submit it. I did not use `_template_addon_release.json`, but I used scons with some version of buildvars.py.

I been very busy lately with MathML discussions and have not paid close attention to all the discussions about the changes for addons. I tried to follow the instructions on the addon store github for submissions, but they don't discuss what to do for the build (using scons or whatever). What's the URL that says that. I want to keep my build up to date with the current guidelines.

**Comment by NSoiffer** [comment]
Thanks for that info. I have updated the MathCAT build. The addon is at https://github.com/NSoiffer/MathCATForPython/releases/download/0.2.1/MathCAT-0.2.1.nvda-addon

The .json file is shown below (sorry can't attach it with suffix .json in github). Note that the addon id uses CamelCase ("addonId": "MathCAT"). I hope this helps.

Thanks for all your help with this and the store.
```
{
	"addonId": "MathCAT",
	"displayName": "MathCAT: speech and braille from MathML",
	"URL": "",
	"description": "\n\t\tMathCAT is a replacement for MathPlayer which has been discontinued.\n\t\tIt provides speech and braille support, and also supports MathPlayer's three modes of navigation.\n\t\tThe speech quality is not quite as good as MathPlayer's speech yet,\n\t\tbut the braille support is much better and includes both Nemeth and UEB Technical.\n\t\tTranslations to languages other than English are in progress.\n\t\t",
	"sha256": "5ce5852776e1ee2e94afb01898e88f9c1c403838601f282cf152c57413f34aee",
	"homepage": "https://nsoiffer.github.io/MathCAT/",
	"addonVersionName": "0.2.1",
	"addonVersionNumber": {
		"major": 0,
		"minor": 2,
		"patch": 1
	},
	"minNVDAVersion": {
		"major": 2018,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2023,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "",
	"sourceURL": "https://github.com/NSoiffer/MathCATForPython",
	"license": "MIT and GPL 2",
	"licenseURL": "https://raw.githubusercontent.com/NSoiffer/MathCAT/main/LICENSE"
}
```

**Comment by josephsl** [comment]
Hi, in this case, let’s close this one, wait until lowercase to uppercase conversion is done, then submit 0.2.1. Thanks.

**Comment by NSoiffer** [comment]
Hopefully this is done before 2023.1 is released. The current addon will
fail there because the latest compatible version is listed as 2022.1.

**Comment by josephsl** [comment]
Hi, in this case, I think a better solution is wait until 2023.1 stable version is released, at which point see if lowercase to uppercase conversion is done, then release 2023.1 compatible version of MathCAT (the reason: NV Access folks have returned from attending CSUN conference, so I think they need some rest before returning to work). Thanks.

**Comment by josephsl** [comment]
Good news - lowercase to uppercase conversion is complete, so let's get new MathCAT release out to users. Thanks for your patience.

**Comment by seanbudd** [comment]
Closing this submission as the URL is invalid
