### ISSUE TITLE
[Submit add-on]: easyTableNavigator 2.5

### ISSUE THREAD

**Issue by CoBC** [nvaccess/addon-datastore#2931]
### Download URL

https://github.com/CoBC/easyTableNavigator-1/releases/download/v2.5/easyTableNavigator-v2.5.nvda-addon

### Source URL

https://github.com/CoBC/easyTableNavigator-1

### Publisher

Corentin Bacqué-Cazenave

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by CoBC** [comment]
Don't understand the issue here :(
Can someone help me? CC @seanbudd @CyrilleB79

**Comment by lukaszgo1** [comment]
The version for your add-on is specified as `v2.5` in the manifest, so it cannot be parsed. It should be just `2.5`.

**Comment by CyrilleB79** [comment]
@seanbudd, the error message is actually not very explicit. Can we improve this?
