### ISSUE TITLE
[Submit add-on]: ObjPad 24.04 - Compatibility/Translation Update

### ISSUE THREAD

**Issue by ChrisDuffley** [nvaccess/addon-datastore#3042]
### Download URL

https://github.com/ChrisDuffley/objPad/releases/download/24.04/objPad-24.04.nvda-addon

### Source URL

https://github.co/ChrisDuffley/objPad

### Publisher

ChrisDuffley

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by ChrisDuffley** [comment]
@michaelDCurran: Should I close this issue and make a new one?

Thanks!

**Comment by ChrisDuffley** [comment]
@michaelDCurran, OH never mind, I see that the approval PR was never merged now...hmm...

**Comment by michaelDCurran** [comment]
I'm not too sure what is going on with the system. Could you pleas re-submit your issue? You have  been added to submitters for objpad now. So assuming the github action does run again, then  it should be submitted fine.

**Comment by ChrisDuffley** [comment]
Thank you! Will do.
Chris
