### ISSUE TITLE
[Submit add-on]: Speak typing words enhancement 2024.0.3

### ISSUE THREAD

**Issue by javidominguez** [nvaccess/addon-datastore#3141]
### Download URL

https://github.com/javidominguez/speakTypingWords/releases/download/2024.0.3/speakTypingWords-2024.0.3.nvda-addon

### Source URL

https://github.com/javidominguez/speakTypingWords/

### Publisher

Javi Dominguez

### Channel

dev

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by XLTechie** [comment]
@javidominguez Should this perhaps be called "Speak Typed Words Enhancement"? 
"Speak typed words" is the feature name in English.

**Comment by javidominguez** [comment]
You are probably right, my English is not very good. I would not change the internal name because it would cause problems for some users who already have it installed but I can change the summary. Can I replace the asset in the release now or should I close this issue and open a new one after changing it? The link would be the same but the file and its hash would not.

**Comment by CyrilleB79** [comment]
The best practice would be to make a new release, i.e. increase the version number, in case someone has already downloaded the add-on directly from your GitHub.

Anyway, if you still choose to keep the same download link / version number, I'd recommend to close this issue though, and open a new one.

**Comment by javidominguez** [comment]
In addition to the poor translation, I have discovered an error whereby the addon would not work for some users in certain circumstances. I'm going to correct it. I close and will reopen a new one.
