### ISSUE TITLE
[an updated version of resourceMonitor]: 

### ISSUE THREAD

**Issue by kefaslungu** [nvaccess/addon-datastore#323]
### Download URL

https://github.com/kefaslungu/resourceMonitor/releases/download/23.04.1/resourceMonitor23.04.1.nvda-addon

### Source URL

https://github.com/kefaslungu/resourceMonitor

### Publisher

Kefas Lungu

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by josephsl** [comment]
Hi,

Huh? How come this was closed manually by Kefas, not by the GitHub Actions bot? This explains why 23.04.1 didn't make out to add-on datastore...

Thanks.
