### ISSUE TITLE
Weekday

### ISSUE THREAD

**Issue by DollaR84** [nvaccess/addon-datastore#3238]
### Download URL

https://github.com/DollaR84/weekday/releases/download/v1.0.0/weekday-1.0.0.nvda-addon

### Source URL

https://github.com/DollaR84/weekday

### Publisher

Ruslan Dolovaniuk

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by nvdaes** [comment]
Just to notice that in the store there is an add-on withthe name Day of the week.
cc: @abdel792

**Comment by DollaR84** [comment]
I saw this addon, but it solves a completely different problem.
My add-on also has a whole range of functions.
Maybe it's worth renaming, it just started with the day of the week
