### ISSUE TITLE
[Submit add-on]: 

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/addon-datastore#3258]
### Download URL

https://github.com/nvdaes/clipContentsDesigner/releases/download/31.0.0/clipContentsDesigner-31.0.0.nvda-addon

### Source URL

https://github.com/nvdaes

### Publisher

nvdaes

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by nvdaes** [comment]
Sorry, this wa resubmitted here accidentally

**Comment by XLTechie** [comment]
@nvdaes even if this was a mistake, shouldn't the automation have kicked in and opened a PR by now? I'm a little disturbed that it hasn't.

This is the first submission since the CodeQL merge I believe.

**Comment by nvdaes** [comment]
@XLTechie , I think that a PR shouldn't opened since the add-on exists in the store with the same version, so the workflow is interrupted before.
