### ISSUE TITLE
Resource Monitor (critical): reverting 23.04/23.0.4/23.04.1 releases

### ISSUE THREAD

**Issue by josephsl** [nvaccess/addon-datastore#330]
Hi all,

Due to an issue coming from Resource Monitor repository where an add-on template file was edited that should not have been edited, I will create a pull request to revert Resource Monitor 23.04/23.0.4/23.04.1 releases altogether. This will result in 23.02.1 being offered to users. After the pull request comes to add-on datastore, I will submit Resource Monitor 23.04.2 as a direct replacement.

Thanks.

**Comment by seanbudd** [comment]
Hi Joseph - can this be closed?

**Comment by josephsl** [comment]
Hi, yes please. Thanks.
