### ISSUE TITLE
[Submit add-on]: gestorDeEnlaces

### ISSUE THREAD

**Issue by AAyoubelbakhti** [nvaccess/addon-datastore#3340]
### Download URL

https://github.com/AAyoubelbakhti/Gestor-De-Enlaces-para-NVDA/releases/download/v1.1.2/gestorDeEnlaces-1.1.2.nvda-addon

### Source URL

https://github.com/AAyoubelbakhti/Gestor-De-Enlaces-para-NVDA

### Publisher

Ayoub

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by seanbudd** [comment]
Hi - it appears you have changed the file since submitting.
Please note that changing releases after submission will prevent users from downloading the add-on with NVDA.
Any release URL should always return the exact same file with the exact same file hash.
