### ISSUE TITLE
[Submit add-on]: scanvox for NVDA dev

### ISSUE THREAD

**Issue by Nael-Sayegh** [nvaccess/addon-datastore#3353]
### Download URL

https://github.com/Nael-Sayegh/scanvox-for-nvda/releases/download/2024.04.30-dev/scanvox-2024.04.30-dev.nvda-addon

### Source URL

https://github.com/Nael-Sayegh/scanvox-for-nvda

### Publisher

Nael Sayegh

### Channel

dev

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by seanbudd** [comment]
The add-on version number you provide in the manifest is invalid.
To be submitted to the add-on store it must follow the pattern `X.X` or `X.X.X`
