### ISSUE TITLE
Weekday[Submit add-on]: 

### ISSUE THREAD

**Issue by DollaR84** [nvaccess/addon-datastore#3408]
### Download URL

https://github.com/DollaR84/weekday/releases/download/v1.0.0/weekday-1.0.0.nvda-addon

### Source URL

https://github.com/DollaR84/weekday

### Publisher

Ruslan Dolovaniuk

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by seanbudd** [comment]
This version was submitted and accepted weeks ago #3240
It appears the download link 404s now.
