### ISSUE TITLE
[Submit add-on]: Note diary

### ISSUE THREAD

**Issue by JohanAnim** [nvaccess/addon-datastore#3424]
### Download URL

https://github.com/JohanAnim/Note-diary/releases/download/2024.1.0/Note.diary.for.NVDA-2024.1.0.nvda-addon

### Source URL

https://github.com/JohanAnim/Note-diary

### Publisher

Johan G

### Channel

stable

### License Name

GPL v3

### License URL

https://www.gnu.org/licenses/gpl-3.0.html

**Comment by JohanAnim** [comment]
Hello,Yes I am the owner of this repository.Ok, thank you very much, I will wait for you to review it, and I would like to have a question answered please: When my plugin is published, how would I update it later?Thank you in advance for everything. Enviado desde Correo para Windows De: github-actions[bot]Enviado: miércoles, 8 de mayo de 2024 09:10 a. m.Para: nvaccess/addon-datastoreCC: JohanAnim; AuthorAsunto: Re: [nvaccess/addon-datastore] [Submit add-on]: Note diary (Issue #3424) Welcome to the add-on store submission process.As this is your first submission for Note diary for NVDA, you will need manual approval as a submitter.If you are not the owner of the main repository for this add-on, please provide evidence that you have permission to submit this add-on.Please wait until #3425 is merged.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by seanbudd** [comment]
Closing as duplicate #3435
