### ISSUE TITLE
[Submit add-on]: 

### ISSUE THREAD

**Issue by JohanAnim** [nvaccess/addon-datastore#3430]
### Download URL

https://github.com/JohanAnim/Note-diary/releases/download/noteDiary/Note.diary.for.NVDA-v2024.1.0.nvda-addon

### Source URL

https://github.com/JohanAnim/Note-diary

### Publisher

Johan G

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by seanbudd** [comment]
Why did you submit this so many times?  it makes it very hard to track submissions
Closing as duplicate #3435
