### ISSUE TITLE
[Submit add-on]: notediary

### ISSUE THREAD

**Issue by JohanAnim** [nvaccess/addon-datastore#3434]
### Download URL

https://github.com/JohanAnim/Note-diary/releases/download/2024.1.0/Note_diary_for_NVDA-v2024.1.0.nvda-addon

### Source URL

https://github.com/JohanAnim/Note-diary

### Publisher

Johan G

### Channel

stable

### License Name

GPL v3

### License URL

https://www.gnu.org/licenses/gpl-3.0.html

**Comment by seanbudd** [comment]
Why did you submit this so many times?  it makes it very hard to track submissions
Closing as duplicate #3435

**Comment by JohanAnim** [comment]
Hello, Yes, I'm really sorry, but I still didn't understand how sending accessories to the store works.But I already managed to understand everything well, I really do, this is the final one that I want to upload:https://github.com/nvaccess/addon-datastore/pull/3438 So thank you very much in advance. Enviado desde Correo para Windows De: Sean BuddEnviado: viernes, 10 de mayo de 2024 12:58 a. m.Para: nvaccess/addon-datastoreCC: JohanAnim; AuthorAsunto: Re: [nvaccess/addon-datastore] [Submit add-on]: notediary (Issue #3434) Why did you submit this so many times? it makes it very hard to track submissionsClosing as duplicate #3435—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
