### ISSUE TITLE
[Submit add-on]: NVDA Remote 2.6

### ISSUE THREAD

**Issue by josephsl** [nvaccess/addon-datastore#354]
### Download URL

https://github.com/NVDARemote/NVDARemote/releases/download/v2.6/remote-2.6.nvda-addon

### Source URL

https://github.com/NVDARemote/NVDARemote

### Publisher

nvdaremote

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by nvdaes** [comment]
>i think you will have to resubmit this when issue 21 of addon-datastore-validation is fixed. I"ve closed an issue to send again reportPasswords add-on, to finish my migration from legacy. I suppose that issue 21 will be fixed asap since it"s a regression introduced today.

**Comment by josephsl** [comment]
Will return with take 2 once validation repo issue is fixed. Thanks.

**Comment by seanbudd** [comment]
Closing as invalid
