### ISSUE TITLE
BrowserNav v2.5[Submit add-on]: 

### ISSUE THREAD

**Issue by mltony** [nvaccess/addon-datastore#3668]
### Download URL

https://github.com/mltony/nvda-browser-nav/releases/download/v2.5/browsernav-2.5.nvda-addon

### Source URL

https://github.com/mltony/nvda-browser-nav/

### Publisher

Tony Malykh

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by seanbudd** [comment]
This has already been submitted: https://github.com/nvaccess/addon-datastore/blob/master/addons/browsernav/2.5.0.json
