### ISSUE TITLE
Re submit espeakWitMbrola v1.0.3

### ISSUE THREAD

**Issue by FelipeZanabria** [nvaccess/addon-datastore#3687]
### Download URL

https://github.com/FelipeZanabria/Espeak-wit-Mbrola/releases/download/1.0.3/espeakWitMbrola-1.0.3.nvda-addon

### Source URL

https://github.com/FelipeZanabria/Espeak-wit-Mbrola

### Publisher

Felipe Porciuncula Zanabria

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by seanbudd** [comment]
Hi - we currently do not support resubmissions of add-ons. Can you please clarify why you are resubmitting?

**Comment by FelipeZanabria** [comment]
The same version.

**Comment by seanbudd** [comment]
Yes, the add-on store doesn't support modification of existing add-ons. Please re-release
