### ISSUE TITLE
[Submit add-on]: Gestor de Pomodoros 1.8

### ISSUE THREAD

**Issue by jpavonabian** [nvaccess/addon-datastore#3739]
### Download URL

https://github.com/jpavonabian/Gestor-de-Pomodoros/releases/download/v1.8/gestorDePomodoros-1.8.nvda-addon

### Source URL

https://github.com/jpavonabian/Gestor-de-Pomodoros/

### Publisher

Jesús Pavón abián

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by jpavonabian** [comment]
@seanbudd can you help me?
Some time ago I opened an isue to try to upload this version, but I left it
aside. I know there was a problem with the store so I decided to open a new
isue to see if the problem was fixed.
What can I do to fix this error?
Thanks in advance.

**Comment by seanbudd** [comment]
@jpavonabian - it appears you have changed the casing pattern of the add-on ID. This is not supported.
You can either:
- resubmit using the old casing `GestorDePomodoros` in the manifest
- open a PR to update this file changing the folder name and add-on ID: https://github.com/nvaccess/addon-datastore/blob/master/addons/GestorDePomodoros/1.1.1.json

See also the guide here: https://github.com/nvaccess/addon-datastore/blob/master/docs/submitters/migratingFromAddonFiles.md#updating-casing-to-lowercamelcasing

**Comment by jpavonabian** [comment]
Thanks!
