### ISSUE TITLE
[Submit add-on]: askChatGPT version 0.20

### ISSUE THREAD

**Issue by mo29cg** [nvaccess/addon-datastore#3881]
### Download URL

https://github.com/mo29cg/nvda-chatGPT/releases/download/v0.20/nvdaChatGPT-0.20.nvda-addon

### Source URL

https://github.com/mo29cg/nvda-chatGPT

### Publisher

Satoshi Suzuki

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by mo29cg** [comment]
I sent a review request to,
tech@maxpcsecure.com

**Comment by jmdaweb** [comment]
Good luck, you will need it.

**Comment by mo29cg** [comment]
Newer version (0.21) with updated dependencies is accepted.
So, I turn down this submit request.
