### ISSUE TITLE
Allow 'dev' version of add-on

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/addon-datastore#40]
The add-on datastore system currently has:
- `stable` - Add-ons that are considered release quality for a released version of NVDA.
- `beta` - Add-ons that are pre-release quality for a released version of NVDA.

There is no category for "pre-release add-on for pre-release NVDA". This category is important to allow ["dogfooding"](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) by add-on developers to while developing against alpha. This is particularly important during compatibility breaking releases; NV Access wants to facilitate early feedback from add-on developers when changes are made to the NVDA API available for add-ons, for this there must be a low-friction way for add-on developers (and a dev audience) to test out the changes.

Adding a `dev` version could, allowing submissions for Add-on API versions yet to be released (read: relaxing the Add-on API compatibility constraints imposed by the addon-datastore-validation repo when the submission is in the dev channel) could help to alleviate this, giving:
- stable add-ons - final/release/stable, being developed for an already released version of NVDA.
- beta add-ons - Pre-release, being developed for an already released version of NVDA (I.E. it has been added to the [set of available releases](https://github.com/nvaccess/addon-datastore-transform/blob/main/nvdaAPIVersions.json) in the [addon-datastore-transform repo](https://github.com/nvaccess/addon-datastore-transform))
- dev add-ons - Pre-release, being developed for currently in alpha/beta/rc version of NVDA.

Ensure that definitions in the readme are updated to match.
Currently it says (in the [Considerations section](https://github.com/nvaccess/addon-datastore#considerations)):
>- Enable support in the store for 'beta' add-ons, for instance:
>  - add-ons being developed against alpha / beta NVDA.
>  - add-ons that want early feedback from end users.
>  - End users can choose "show me beta add-ons"

It should become:
>- Enable support in the store for 'beta' and 'dev' add-ons, for instance:
>  - 'dev' add-ons are being developed against alpha / beta / rc NVDA, these would only be offered to alpha / beta / rc NVDA users.
>  - 'beta' add-ons are from authors who want early feedback from end users, signaling that not all edge cases are handled.
>  - End users of NVDA can select "show pre-release add-ons"

**Comment by nvdaes** [comment]
In the readme of this repo we can see:

> • Enable support in the store for 'beta' add-ons, for instance: 
◦ add-ons being developed against alpha / beta NVDA.
◦ add-ons that want early feedback from end users.

Then, seems that beta is similar to the proposed dev version. We may need clarification of definitions, in particular, if dev versions for NVDA 2.22.1alpha can declare to be tested against 2022.1 even when the API is not frozen.
Also, released versions of NVDA may need further clarifications, since candidate release are releases too, not just stable versions.
pepens

**Comment by nvdaes** [comment]
This seems to be similar to the proposed dev versions.
We may need clarifications for definitions, in particular for the requirements of the lastTestedNVDAVersion in manifest.ini, for example, if dev versions can state to be tested against 2022.1 even when API is not frozen.
And about releases, if rc are considered releases too.

**Comment by feerrenrut** [comment]
The definitions in this issue are:
- stable add-ons - final/release/stable, being developed for an already released version of NVDA.
- beta add-ons - Pre-release, being developed for an already released version of NVDA.
- dev add-ons - Pre-release, being developed for currently in alpha version of NVDA.

Hope this clarifies.

**Comment by nvdaes** [comment]
Definitions are clear. A PR maybe created to modify the readme, where beta versions of add-on are supposed to work for alpha/beta versions of NVDA.

**Comment by feerrenrut** [comment]
For handling the pre-release NVDA side of the equations see https://github.com/nvaccess/addon-datastore-transform/issues/15

**Comment by seanbudd** [comment]
Related PRs:
- [ ] https://github.com/nvaccess/addon-datastore-validation/pull/14
