### ISSUE TITLE
[Submit add-on]: ReferenceStyler

### ISSUE THREAD

**Issue by jasonpython50** [nvaccess/addon-datastore#4098]
### Download URL

https://github.com/jasonpython50/referenceStyler/releases/tag/v24.0.0

### Source URL

https://github.com/jasonpython50/referenceStyler

### Publisher

Asamoah Emmanuel

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by XLTechie** [comment]
@jasonpython50, you gave the wrong URL for downloading the add-on.

You listed the URL to the release. The one you should have given in the first field, needs to be the release asset. In your case I believe that's:

https://github.com/jasonpython50/referenceStyler/releases/download/v24.0.0/referenceStyler-24.0.0.nvda-addon
