### ISSUE TITLE
[Submit add-on]: referenceStyler

### ISSUE THREAD

**Issue by jasonpython50** [nvaccess/addon-datastore#4099]
### Download URL

https://github.com/jasonpython50/referenceStyler/releases/download/v24.0.0/referenceStyler-24.0.0.nvda-addon

### Source URL

https://github.com/jasonpython50/referenceStyler

### Publisher

Asamoah Emmanuel

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by jasonpython50** [comment]
I was wondering how long it takes for an addon to be approved and submitted to the addon store

**Comment by XLTechie** [comment]
@jasonpython50 For the first release, a few days or a week, usually.

After that (for subsequent releases), the process is all automated, and it takes around half an hour.

**Comment by jasonpython50** [comment]
Luke, you have been so helpful since the I joined the addon mailing list for the first time. You were the first person to respond to my queries and yet you came in to support when I was finding it more difficult to submit my first addon. This is greatly appreciated and it means a lot to me. Thank you so much.
Swimmingly,

**Comment by XLTechie** [comment]
Asamoah, you are very welcome. Glad I could be of some assistance.
