### ISSUE TITLE
EnhancedFindDialog 1.6.0

### ISSUE THREAD

**Issue by marlon-sousa** [nvaccess/addon-datastore#4240]
### Download URL

https://github.com/marlon-sousa/EnhancedFindDialog/releases/download/1.6.0/EnhancedFindDialog-1.6.0.nvda-addon

### Source URL

https://github.com/marlon-sousa/enhancedFindDialog

### Publisher

Marlon Sousa

### Channel

stable

### License Name

Mit License

### License URL

https://github.com/marlon-sousa/EnhancedFindDialog/blob/master/LICENSE

**Comment by seanbudd** [comment]
Hi @marlon-sousa - there was a very mysterious error happening here. Please disregard
