### ISSUE TITLE
Automatically merge virus total URL PRs

### ISSUE THREAD

**Issue by SaschaCowley** [nvaccess/addon-datastore#4455]
Currently, a job is periodically run to add VirusTotal URLs to their add-on metadata files. However, the PR created by this job needs too be manually merged. If it is safe to do so, these PRs should automatically be merged.

**Comment by seanbudd** [comment]
fixed in https://github.com/nvaccess/addon-datastore/commit/21bc09becb8bc650e6f10ec4d19c68ed92652367 and f214a2fe52
