### ISSUE TITLE
[Submit add-on]: 

### ISSUE THREAD

**Issue by diamondStar35** [nvaccess/addon-datastore#4463]
### Download URL

https://github.com/diamondStar35/clipManager/releases/download/v0.1/clipManager0.1.nvda-addon

### Source URL

https://github.com/diamondStar35/clipManager/

### Publisher

Abdalrahmen Maher

### Channel

stable

### License Name

GPL v3

### License URL

https://www.gnu.org/licenses/gpl-3.0.html

**Comment by seanbudd** [comment]
@diamondStar35 - you have submitted two add-on IDs which are very similar but different. `clip_manager` and `clipManager`. which one do you intend to use? Please don't change your add-on ID across releases, NVDA will treat it as an entirely different add-ons which can cause conflicts.

**Comment by diamondStar35** [comment]
HelloThe first issue was closed, And the second issue is the correct add-on ID which is “clipManager” which I intend to use.Regards.   From: Sean BuddSent: Friday, November 8, 2024 5:40 AMTo: nvaccess/addon-datastoreCc: Abdalrahmen Maher; MentionSubject: Re: [nvaccess/addon-datastore] [Submit add-on]: (Issue ***@***.*** - you have submitted two add-on IDs which are very similar but different. clip_manager and clipManager. which one do you intend to use? Please don't change your add-on ID across releases, NVDA will treat it as an entirely different add-ons which can cause conflicts.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
