### ISSUE TITLE
[Submit add-on]: EnhancedFindDialog 1.6.1

### ISSUE THREAD

**Issue by marlon-sousa** [nvaccess/addon-datastore#4552]
### Download URL

https://github.com/marlon-sousa/EnhancedFindDialog/releases/download/1.6.1/EnhancedFindDialog-1.6.1.nvda-addon

### Source URL

https://github.com/marlon-sousa/EnhancedFindDialog

### Publisher

Marlon Sousa

### Channel

stable

### License Name

Mit License

### License URL

https://github.com/marlon-sousa/EnhancedFindDialog/blob/master/LICENSE

**Comment by marlon-sousa** [comment]
I cannot download the report, as the download link seems to point to the issue itself.

I suppose @feerrenrut  that this is the same problem we had in the submission of the previous version of this addon.

**Comment by marlon-sousa** [comment]
indeed, it is the same error:

https://github.com/nvaccess/addon-datastore/actions/runs/11809586216/job/32900249126

Remove-Item: Cannot find path 'D:\a\addon-datastore\addon-datastore\addon\locale\hr\manifest.ini' because it does not exist.

**Comment by XLTechie** [comment]
Please don't CC feerrenrut; he hasn't been with NV Access for some years.
@seanbudd is who you want, and he will see this as open already.

**Comment by marlon-sousa** [comment]
Ok. Edited the comment.

As for him being automatically subscribed I was not sure so I marked him.

Thanks

**Comment by seanbudd** [comment]
Apologies @marlon-sousa - I've been out of office lately
