### ISSUE TITLE
Excel explorer

### ISSUE THREAD

**Issue by Younizia74** [nvaccess/addon-datastore#4583]
### Download URL

https://drive.google.com/file/d/15JLFRggvDmbREFVeGfD_WnosjGTL5zMG/view?usp=drivesdk

### Source URL

https://drive.google.com/file/d/1RzhnJ7V7XzZiXI8HBj0CxLHoU-yzA_wF/view?usp=drivesdk

### Publisher

Kevin Chatellard 

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by josephsl** [comment]
Hello,

Thanks for submitting Excel Explorer. The submission process does not take things other than the direct link to the NVDA add-on file. Also, when trying to access the submitted download link and the source link, Google says "access is denied", making it difficult to verify the add-on and its contents. In the future, please provide the direct download link (.nvda-addon file) and a public link to the add-on source code (typiclaly GitHub).

Thanks.

**Comment by Younizia74** [comment]
@josephsl
Hello, 

thank you for your comment. In fact, I shared some restricted-access links without paying any attention to them!

This is extremely disabling for accessing their content, I admit.
I'll be more careful in the future.

**Comment by Younizia74** [comment]
Hello, I have fixed the fact that the files inaccessible with their Link

On the other hand a JSON file but still
Request

What should I do?
Sincerely

**Comment by Younizia74** [comment]
> Bonjour,
Après réflexion, je voulais ajouter quelques précisions pour mieux expliquer mon problème :

Le fichier manifest.ini.tpl dans le code source de mon projet est vide, mais je comprends qu’il est censé générer manifest.ini. Je ne sais pas comment le configurer pour que cela fonctionne correctement.

Un fichier JSON m’a été demandé pour soumettre mon add-on, mais je ne suis pas sûr du contenu attendu ni de son lien avec manifest.ini.


Voici ce que j’ai actuellement dans manifest.ini :

name = Excelexplorer2  
summary = "Excel explorer"  
description = "'"'Excel explorer"""  
author = "Mahamadou DOUCOURE <mistofsoundjata2018@gmail .corn>"  
url = https://github.com/mltony/nvda-text-nav  
version = 1 .8  
docFileName = readme.html  
minimumNVDAVersion = 2019.2.0  
lastTestedNVDAVersion = 2024.1.0  
updateChannel = None

Et voici un fichier JSON que j’ai tenté de créer à partir de manifest.ini :

{
    "addon": {
        "name": "Excelexplorer2",
        "summary": "Excel explorer",
        "description": "Excel explorer",
        "author": "Mahamadou DOUCOURE <mistofsoundjata2018@gmail.com>",
        "url": "https://github.com/mltony/nvda-text-nav",
        "version": "1.8",
        "docFileName": "readme.html",
        "minimumNVDAVersion": "2019.2.0",
        "lastTestedNVDAVersion": "2024.1.0",
        "updateChannel": "None"
    }
}

Je serais ravi d’avoir vos retours pour savoir si je suis sur la bonne voie ou s’il y a des ajustements nécessaires. Merci d’avance pour votre aide !
