### ISSUE TITLE
Silenzio V1.0.0

### ISSUE THREAD

**Issue by DarkoMilosevic86** [nvaccess/addon-datastore#4643]
### Download URL

https://github.com/DarkoMilosevic86/Silenzio/releases/download/V1.0.0/Silenzio-1.0.0.nvda-addon

### Source URL

https://github.com/DarkoMilosevic86/Silenzio

### Publisher

Darko Milošević

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by SaschaCowley** [comment]
@DarkoMilosevic86 the download link you have provided does not work, and the repo you link to seems to have been renamed.

**Comment by josephsl** [comment]
Hi all,

See a discussion about it here:

https://nvda-addons.groups.io/g/nvda-addons/topic/silenzio_1_0_0_nvda_addon/109870044

I advise closing this one in favor of a later submission or none as there is an ongoing discussion about the necessity of this and the later submitted add-on at the moment.
