### ISSUE TITLE
[Submit add-on]: 

### ISSUE THREAD

**Issue by DarkoMilosevic86** [nvaccess/addon-datastore#4655]
### Download URL

https://github.com/DarkoMilosevic86/BluetoothAudioActive/releases/download/v1.0.0/BluetoothAudioActive-1.0.0.nvda-addon

### Source URL

https://github.com/DarkoMilosevic86/BluetoothAudioActive

### Publisher

Darko Milosevic

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by josephsl** [comment]
Hi all,

I usually do not comment on new add-on submissions, or if I do, generally agree with getting the add-on to the store. However, given the discussion here:

https://nvda-addons.groups.io/g/nvda-addons/topic/silenzio_1_0_0_nvda_addon/109870044

I would like to request that we be considerate of diverse viewpoints in the linked thread, including acceptance, reconsideration, rejection (do not accept the add-on), or redirection (to resolve the problem through Silenzio utility itself, not this add-on). I fall between redirection and rejection camps - let the utility developer handle this as the ability to keep a wireless audio device open is part of NVDA.

Thanks.

**Comment by seanbudd** [comment]
@josephsl - we do not reject add-ons from the store on merit of usefulness. We only reject malicious add-ons and add-ons which breach our code of conduct
