### ISSUE TITLE
[Submit add-on]: 

### ISSUE THREAD

**Issue by mehranlatifi83** [nvaccess/addon-datastore#4749]
### Download URL

https://github.com/mehranlatifi83/v2rayN/releases/download/v0.1/v2rayN-0.1.nvda-addon

### Source URL

https://github.com/mehranlatifi83/v2rayN/

### Publisher

Mehran Latifi

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by SaschaCowley** [comment]
@mehranlatifi83 per https://github.com/nvaccess/addon-datastore/issues/4749#issuecomment-2555775230, It did not fail, you need to wait for manual approval when submitting a given add-on for the first time.
