### ISSUE TITLE
[Submit add-on]: Visma Administration

### ISSUE THREAD

**Issue by towebo** [nvaccess/addon-datastore#501]
### Download URL

https://github.com/towebo/VismaAdministration-NVDAAddOn/releases/download/v2023.0.0/vismaAdministration-2023.0.nvda-addon

### Source URL

https://github.com/towebo/VismaAdministration-NVDAAddOn

### Publisher

Karl-Otto Rosenqvist

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by seanbudd** [comment]
Hi @towebo,

Your submission failed due to an error in the manifest.
The minimum required version: 2021.0.0 doesn't exist. It should be 2021.1 or 2021.1.0
