### ISSUE TITLE
[Submit add-on]: IntelliJ Improved

### ISSUE THREAD

**Issue by SamKacer** [nvaccess/addon-datastore#510]
### Download URL

https://github.com/SamKacer/IntelliJ_NVDA_Addon/releases/download/v1.3.2/IntelliJImproved-1.3.2.nvda-addon

### Source URL

https://github.com/SamKacer/IntelliJ_NVDA_Addon                                                                                                                                                                  

### Publisher

Samuel Kacer

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by SamKacer** [comment]
I think for some reason, this didn't triggr the creation of a PR

**Comment by XLTechie** [comment]
It does look like it didn't. Perhaps close it and submit again? If doing it again doesn't trigger, wait for NV Access opinion.

**Comment by seanbudd** [comment]
The `minimumNVDAVersion` is invalid in your manifest file. It is currently set to `None`. It should be `0.0.0` or another valid NVDA  API version

**Comment by seanbudd** [comment]
I'll look into handling this error better in future
