### ISSUE TITLE
Request to merge "bluetoothaudio" and "btaudio" into one

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/addon-datastore#621]
Hello,

I created two repos when releasing the 'Blue Tooth Audio Version1.5' add-on,

I want to merge the existing 'btaudio' with the 'bluetoothaudio' I created yesterday, and finally keep one.

Probably for the same reason, 'Blue Tooth Audio' on the community site has not been updated either.

As for which one to keep in the end, I'm leaning towards 'bluetoothaudio', however feel free to use whatever works best for you.

I'm so sorry for my mistake.

Thanks

**Comment by XLTechie** [comment]
You should be able to issue your own pull request to delete the unwanted btaudio 
directory. Then all NV Access has to do is merge it at their convenience.

**Comment by cary-rowen** [comment]
Thanks for telling me this.
But I'm wondering, if I remove 'btaudio', will it affect the BlueToothAudio on the community add-ons site?

**Comment by seanbudd** [comment]
Please follow the instructions here: https://github.com/nvaccess/addon-datastore/blob/master/docs/submitters/migratingFromAddonFiles.md

**Comment by cary-rowen** [comment]
Hi @seanbudd 
I finally decided to keep bluetoothaudio and have done that so far, does the original btaudio require me to open a pr for removal?

**Comment by seanbudd** [comment]
Thanks @cary-rowen - you are not required to remove the old add-on but you are welcome to. Removing it may reduce confusion.

**Comment by seanbudd** [comment]
I am closing this as complete
