### ISSUE TITLE
[Submit add-on]: Note-diary 2023.1

### ISSUE THREAD

**Issue by JohanAnim** [nvaccess/addon-datastore#715]
### Download URL

https://github.com/JohanAnim/Note-diary/releases/download/2023.1/Note.diary.for.NVDA-2023.1.nvda-addon

### Source URL

https://github.com/JohanAnim/Note-diary

### Publisher

Johan A G

### Channel

stable

### License Name

GPL v3

### License URL

https://www.gnu.org/licenses/gpl-3.0.html

**Comment by seanbudd** [comment]
Hi @JohanAnim . It appears that the download link has changed for this submission.
The add-on store requires submissions to have a permanent link - the download contents should never change.
For security reasons we need to ensure that the file downloaded by the user is the same file submitted to the add-on store.
This why we cache the checksum SHA, and confirm the checksum when downloading.
Updating the release link will make it unavailable to install through the NVDA add-on store.

Additionally, the add-on ID for note diary is quite unusual. It should probably not contain any spaces.

**Comment by seanbudd** [comment]
Hi @JohanAnim - have you seen this?
