### ISSUE TITLE
Migrating add-ons: some add-on ID's will have duplicate entries differing by case

### ISSUE THREAD

**Issue by josephsl** [nvaccess/addon-datastore#89]
Hi,

While migrating my add-ons to the add-on store, I'm noticing that there are add-ons that will have add-on ID/folder name conflicts (I use add-on name field from the manifest as add-on ID). Examples include evttracker versus evtTracker (the latter is the add-on ID I plan to use), officedesk versus officeDesk, and possibly others. As much as I would like to use the add-on name from the manifest (camel case names) as add-on ID, if lowercase names are to be used, I'll abide by it. Note that the two examples I listed are add-ons I'm no longer maintaining.

Thanks.

**Comment by seanbudd** [comment]
the legacy end point is case insensitive.

If there is existing casing committed to `views` which needs to be amended, please open a PR to amend the casing of the source files in this repo.

**Comment by seanbudd** [comment]
For example `./addons/evttracker` can be updated to  `./addons/evtTracker` in a separate PR

**Comment by josephsl** [comment]
Hi, will do this week as part of adding official 23.02.1 releases to the store repo for continuity purposes and to lay the foundation for future releases. Thanks for the clarification.

**Comment by josephsl** [comment]
Hi,

Update: there are add-ons where there is a mismatch between manifest name field and what is actually shown in add-on datastore (Newfon, for example). I think it would be best to talk to add-on authors about these at some point. As far as I know, only a select add-ons do exhibit this isuse as of March 13, 2023 (Newfon bein one of them).

Thanks.
