### ISSUE TITLE
Migrating add-ons: duplicate entries due to legacy versus actual ad-don ID's

### ISSUE THREAD

**Issue by josephsl** [nvaccess/addon-datastore#90]
Hi,

Follow-up of #89 

There are add-ons that will have duplicate entries, more so if they use legacy add-on ID's. For example, Resource Monitor (add-on ID to use: resourceMonitor) is also listed under the ID of "rm". I myself will use the add-on name field from manifest as add-on ID and plan to submit Resource Monitor 23.04 under "resourceMonitor" ID.

The short names (legacy add-on files repo) were chosen to keep the add-on keys short to help translators translate add-on docs on community add-ons website easily (probably due to Ikiwiki limitations).

Thanks.

**Comment by seanbudd** [comment]
Duplicates are intended to maintain legacy links on ikiwiki.

**Comment by seanbudd** [comment]
If dependency on the specific addonID (e.g. "rn") is removed from legacy
add-on services, we can eventually remove the duplicate. I would encourage
ikiwiki and other dependencies to migrate over to the new addon IDs, if the
goal is to remove legacy items from the new data store.

**Comment by josephsl** [comment]
Replaced by #218 as the newer issue provides general details.
